# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
#fos_rest:
#    param_fetcher_listener:  false
#    allowed_methods_listener:  false
#    routing_loader: false
#    view:
#        view_response_listener:  true
#    format_listener:
#        rules:
#            - { path: ^/api/v1, prefer_extension: true, fallback_format: json, priorities: [ json ] }
