version: '3'

services:
    php:
        container_name: $COMPOSE_PROJECT_NAME-php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        env_file:
            -   .env.local
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=${REQUEST_HOST:-localhost}
        depends_on:
            - database
        networks:
            - network
        extra_hosts:
            - "host.docker.internal:host-gateway"
    ###> doctrine/doctrine-bundle ###
    database:
        container_name: $COMPOSE_PROJECT_NAME-postgres
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        env_file:
            -   .env.local
        environment:
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data:rw
        networks:
            - network

    nginx:
        container_name: $COMPOSE_PROJECT_NAME-nginx
        image: nginx
        env_file:
            - .env.local
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/templates:/etc/nginx/templates:ro
        ports:
            - "80:80"
        environment:
            - NGINX_SERVER_NAME=${REQUEST_HOST:-localhost}
            - NGINX_PORT=80
        networks:
            - network
        depends_on:
            - php
###< doctrine/doctrine-bundle ###

volumes:
    ###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###

networks:
    network:
